wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1648325145
    t:
      1:
      - 1
      3:
      - 16
      - 35
      4: 3.8.12
      5: 0.12.11
      8:
      - 3
      - 5
policy:
  desc: null
  value: CnnPolicy
total_timesteps:
  desc: null
  value: 250000
